"""Новая таблица для теста

Revision ID: 1c42ba00cb4c
Revises: 8619d6294766
Create Date: 2020-05-10 22:52:14.740152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c42ba00cb4c'
down_revision = '8619d6294766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_code', sa.String(length=140), nullable=True),
    sa.Column('size', sa.String(length=120), nullable=True),
    sa.Column('cloth', sa.String(length=50), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('type', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cloth'), 'test', ['cloth'], unique=False)
    op.create_index(op.f('ix_test_size'), 'test', ['size'], unique=False)
    op.create_index(op.f('ix_test_type'), 'test', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_type'), table_name='test')
    op.drop_index(op.f('ix_test_size'), table_name='test')
    op.drop_index(op.f('ix_test_cloth'), table_name='test')
    op.drop_table('test')
    # ### end Alembic commands ###
