"""add price

Revision ID: 745ec2de863a
Revises: a73c18c6695b
Create Date: 2020-06-04 03:01:12.125686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745ec2de863a'
down_revision = 'a73c18c6695b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thing', sa.Column('price', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_thing_price'), 'thing', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thing_price'), table_name='thing')
    op.drop_column('thing', 'price')
    # ### end Alembic commands ###
