"""Things table

Revision ID: 75c9035e673a
Revises: c049fbaf4083
Create Date: 2020-05-07 07:28:38.737904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c9035e673a'
down_revision = 'c049fbaf4083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_code', sa.String(length=140), nullable=True),
    sa.Column('size', sa.String(length=120), nullable=True),
    sa.Column('cloth', sa.String(length=50), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('type', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thing_cloth'), 'thing', ['cloth'], unique=False)
    op.create_index(op.f('ix_thing_sex'), 'thing', ['sex'], unique=False)
    op.create_index(op.f('ix_thing_size'), 'thing', ['size'], unique=False)
    op.create_index(op.f('ix_thing_type'), 'thing', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thing_type'), table_name='thing')
    op.drop_index(op.f('ix_thing_size'), table_name='thing')
    op.drop_index(op.f('ix_thing_sex'), table_name='thing')
    op.drop_index(op.f('ix_thing_cloth'), table_name='thing')
    op.drop_table('thing')
    # ### end Alembic commands ###
