"""new field in user table

Revision ID: 8619d6294766
Revises: 75c9035e673a
Create Date: 2020-05-07 07:41:51.155331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8619d6294766'
down_revision = '75c9035e673a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_thing_sex', table_name='thing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_thing_sex', 'thing', ['sex'], unique=False)
    # ### end Alembic commands ###
