"""things table

Revision ID: fd86302b9ee7
Revises: 8dd47d9eb806
Create Date: 2020-04-22 21:59:55.309998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd86302b9ee7'
down_revision = '8dd47d9eb806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('things',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thing_name', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_things_thing_name'), 'things', ['thing_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_things_thing_name'), table_name='things')
    op.drop_table('things')
    # ### end Alembic commands ###
